#!/bin/bash
tarname="pa7_olds"
mainclass="wordcount"

# DELETE TAR / CLEAR STAGING
rm $tarname.tar
rm STAGING/*
echo "gitkeep" > STAGING/git.keep
# COPY EVERYTHING TO STAGING
cp src/main/scala/*.scala -r input STAGING
cd STAGING
# TEST - compile / put in jar / delete .class / run
sbt package
# jar -cvf TestJar.jar *.class
# hadoop jar TestJar.jar $mainclass input output
# cat ./output/part-r-00000
# CREATE TAR
tar -cvf ../$tarname.tar *.scala input output
cd ..



###############!!!!!!!!!!!!! CHANGE INPUT BACK ??INPUT-GRAPH
###############!!!!!!!!!!!!! DELETE OUTPUT COMBINING